import risexLogo from "../../assets/risex_logo.jpeg";

export const academy = {
  name: "RiseX Cricket Academy",
  logo: risexLogo,
  tagline: "Fortune Favours The Brave",
  heroHeadline: "Building Skills. Shaping Discipline. Raising Champions.",
  heroSubtext:
    "At RiseX, we don't just train players, we build complete cricketers. With the right coaching, modern facilities and a winning mindset, we prepare you to rise above and achieve your dreams.",
  ctaTagline: "Dream It. Train For It. Achieve It.",
  about:
    "RiseX Cricket Academy is a school-based cricket training academy dedicated to discovering and developing young cricket talent. We partner with schools to provide professional cricket coaching, skill development, fitness training, and regular tournaments within the school environment. Our mission is to make quality cricket coaching accessible to every student and help talented players progress to district, state, and national-level opportunities while building discipline, confidence, teamwork, and sportsmanship.",
  services: [
    ["🏫", "School Cricket Coaching Programs"],
    ["🏏", "In-School Cricket Training Sessions"],
    ["🎯", "Cricket Trial Camps"],
    ["📈", "Skill Development (Batting, Bowling & Fielding)"],
    ["💪", "Fitness & Strength Conditioning"],
    ["🧤", "Wicketkeeping Training"],
    ["🧠", "Match Strategy & Game Awareness"],
    ["🏆", "Inter-School Cricket Tournaments"],
    ["🌟", "Talent Identification & Performance Assessment"],
    ["🎓", "District & State Trial Preparation"],
    ["📊", "Student Progress Reports"],
    ["☀️", "Summer & Winter Cricket Camps"],
    ["👨‍🏫", "Coach Mentorship & Career Guidance"],
    ["🤝", "School Cricket Program Management"],
  ],
  trainingPrograms: [
    ["🏏", "Batting", "Technique, footwork, shot selection & match awareness."],
    ["⚡", "Bowling", "Speed, accuracy, line & length, variations."],
    ["🧤", "Wicketkeeping", "Gloves work, reflexes, footwork & game understanding."],
    ["🤾", "Fielding", "Catching, ground fielding, agility, strength & quick reflexes."],
    ["🧠", "Mental Toughness", "Focus, confidence, decision making & leadership."],
  ],
  whoCanJoin: ["Boys & Girls", "Age 6 Years & Above", "Beginners to Advanced Players"],
  facilities: [
    ["🏟️", "Turf & Net Practice", "High quality practice pitches & professional nets."],
    ["💪", "Fitness & Strength Training", "Improve your stamina, agility & overall performance."],
    ["🎥", "Video Analysis", "Match performance reviews & expert feedback."],
    ["🏆", "Match Exposure", "Regular matches, tournaments & leagues."],
  ],
  badges: ["Certified Coach", "All Age Groups", "Since 2018", "Trial Session Available"],
  stats: [
    ["4", "Active Batches"],
    ["12+", "Years Coaching Experience"],
  ],
  whyChooseUs: [
    [
      "award",
      "Experienced & Certified Coaches",
      "Every session is led by qualified, certified cricket coaches.",
    ],
    [
      "target",
      "Personalized Training Programs",
      "Training plans built around each player's skill level and goals.",
    ],
    [
      "activity",
      "Focus on Skill + Fitness + Mindset",
      "A complete program covering technique, fitness, and the mental game.",
    ],
    [
      "shield",
      "Safe, Positive & Motivational Environment",
      "A supportive space where every player can learn and grow with confidence.",
    ],
    [
      "trending",
      "Pathway to District, State & Professional Cricket",
      "A clear progression path toward district, state, and professional-level cricket.",
    ],
  ],
  programs: [
    {
      title: "Beginners Batch",
      ageGroup: "Ages 8-12",
      description: "Basics of batting, bowling, and fielding, focused on fun and fundamentals.",
      timing: "Mon, Wed, Fri - 6:00 AM to 7:30 AM",
      duration: "3 months",
      fee: "Rs 3,500",
      popular: false,
    },
    {
      title: "School Level Batch",
      ageGroup: "Ages 13-17",
      description:
        "Technique and match practice preparing for school and district selections.",
      timing: "Tue, Thu, Sat - 6:00 AM to 8:00 AM",
      duration: "3 months",
      fee: "Rs 4,500",
      popular: true,
    },
    {
      title: "Advanced / Competitive Batch",
      ageGroup: "Ages 15+",
      description: "Intensive coaching for players targeting club and state-level trials.",
      timing: "Daily - 5:30 AM to 8:00 AM",
      duration: "3 months",
      fee: "Rs 6,000",
      popular: false,
    },
    {
      title: "Weekend Batch",
      ageGroup: "All ages",
      description: "Flexible weekend-only sessions for working professionals and college students.",
      timing: "Sat, Sun - 7:00 AM to 9:00 AM",
      duration: "3 months",
      fee: "Rs 3,000",
      popular: false,
    },
  ],
  phone: "+91 91559 69543",
  whatsapp: "+91 91559 69543",
  email: "risexacademy07@gmail.com",
  address: "Patna, Bihar",
  timings: "Mon - Sun: 5:30 AM - 9:00 AM | Evening batches on request",
};
